name = "filabs/onchain"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for e2e-dapp-example"

[repository]
user = "filabs"
project = "onchain"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
